name: Create an issue
description: Create an issue

inputs:
  title:
    description: Issue title
    required: true
  body:
    description: Issue body
    required: false
  body_file:
    description: Issue body file path
    required: false
  labels:
    description: Comma-separated list of labels
    required: true
  assignees:
    description: Comma-separated list of assignees
    required: false
    default: ""
  append_workflow_info:
    description: Whether to append workflow info to the issue body
    required: false
    default: "true"

outputs:
  issue_number:
    description: Created issue number
    value: ${{ steps.set_output.outputs.issue_number }}

runs:
  using: composite
  steps:
    - name: Prepare issue body
      shell: bash
      env:
        BODY: ${{ inputs.body }}
        BODY_FILE: ${{ inputs.body_file }}
      run: |
        if [[ -n "${BODY}" && -n "${BODY_FILE}" ]]; then
          echo "Error: Both 'body' and 'body_file' inputs are provided. Please provide only one." >&2
          exit 1
        elif [[ -n "${BODY}" ]]; then
          echo "${BODY}" > ${{ runner.temp }}/issue_body.md
        elif [[ -n "${BODY_FILE}" ]]; then
          cp "${BODY_FILE}" ${{ runner.temp }}/issue_body.md
        else
          echo "Error: Neither 'body' nor 'body_file' input is provided. Please provide one." >&2
          exit 1
        fi

    - name: Append workflow info to the issue body
      if: ${{ inputs.append_workflow_info == 'true' }}
      shell: bash
      env:
        GITHUB_WORKFLOW: ${{ github.workflow }}
        GITHUB_RUN_ID: ${{ github.run_id }}
        GITHUB_SHA: ${{ github.sha }}
        GITHUB_REF: ${{ github.ref }}
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_SERVER_URL: ${{ github.server_url }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        cat >> "${{ runner.temp }}/issue_body.md" <<EOF

        **Workflow:** ${ GITHUB_WORKFLOW }
        **Run ID:** ${ GITHUB_RUN_ID }
        **Commit:** ${ GITHUB_SHA }
        **Branch/Ref:** ${ GITHUB_REF }
        **Triggered by:** ${ GITHUB_ACTOR }

        **Workflow run:** ${ GITHUB_SERVER_URL }/${ GITHUB_REPOSITORY }/actions/runs/${ GITHUB_RUN_ID }
        EOF

    - name: Create an issue
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}

        ASSIGNEES: ${{ inputs.assignees }}
        LABELS: ${{ inputs.labels }}
        TITLE: ${{ inputs.title }}

        CREATE_ISSUE_LOG: ${{ runner.temp }}/create_issue.log
      run: |
        gh issue create \
          --title "${TITLE}" \
          --body-file "${{ runner.temp }}/issue_body.md" \
          --label "${LABELS}" \
          --assignee "${ASSIGNEES}" \
          > "${CREATE_ISSUE_LOG}"

    - name: Set output
      id: set_output
      shell: bash
      env:
        CREATE_ISSUE_LOG: ${{ runner.temp }}/create_issue.log
      run: |
        issue_number="$(sed 's|.*/||' "${CREATE_ISSUE_LOG}")"
        echo "issue_number=$issue_number" >> $GITHUB_OUTPUT

        echo "Created issue #${issue_number}"
