name: Prepare runner
description: Install packages, set environment variables, create directories

inputs:
  enable_ccache:
    description: Whether ccache should be enabled
    required: true

runs:
  using: composite
  steps:
    - name: Cleanup workspace
      if: ${{ runner.os == 'macOS' }}
      uses: XRPLF/actions/cleanup-workspace@cf0433aa74563aead044a1e395610c96d65a37cf

    - name: Restart colima
      shell: bash
      run: colima restart

    - name: Spin up scylladb
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      continue-on-error: true
      run: |
        docker rm --force scylladb || true
        docker run \
          --detach \
          --name scylladb \
          --health-cmd "cqlsh -e 'describe cluster'" \
          --health-interval 10s \
          --health-timeout 5s \
          --health-retries 5 \
          --publish 9042:9042 \
          --memory 16G \
          scylladb/scylla

        until [ "$(docker inspect -f '{{.State.Health.Status}}' scylladb)" == "healthy" ]; do
          sleep 5
        done

    - name: Log
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: cat /Users/ec2-user/.colima/_lima/colima/ha.stderr.log
