name: Prepare runner
description: Install packages, set environment variables, create directories

inputs:
  enable_ccache:
    description: Whether ccache should be enabled
    required: true

runs:
  using: composite
  steps:
    - name: Cleanup workspace
      if: ${{ runner.os == 'macOS' }}
      uses: XRPLF/actions/cleanup-workspace@cf0433aa74563aead044a1e395610c96d65a37cf

    - name: Restart colima
      shell: bash
      run: |
        colima stop --force
        rm -rf ~/.colima/default/daemon/
        rm -rf ~/.colima/default/colima.sockets

        colima start

    - name: Log
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: cat /Users/ec2-user/.colima/_lima/colima/ha.stderr.log
