version: 2

updates:
  - package-ecosystem: github-actions
    directory: .github/actions/prepare_runner/
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Etc/GMT
    commit-message:
      prefix: "ci: [DEPENDABOT] "
    target-branch: main
