name: Cleanup GitHub workspace
description: Remove all the files and directories in the GitHub workspace

runs:
  using: composite
  steps:
    - name: Clean the workspace (macOS or Windows)
      if: ${{ runner.os == 'macOS' || runner.os == 'Windows' }}
      shell: bash
      run: |
        WORKSPACE='${{ github.workspace }}'
        if [ -z "${WORKSPACE}" ] || [ "${WORKSPACE}" = "/" ]; then
            echo "Invalid directory: '${WORKSPACE}'"
            exit 1
        fi
        find "${WORKSPACE}" -depth 1 | xargs rm -rfv

    - name: Fail (not macOS or Windows)
      if: ${{ runner.os != 'macOS' && runner.os != 'Windows' }}
      shell: bash
      run: |
        echo "This action only supports macOS and Windows."
        exit 1
