name: Prepare runner
description: Install packages, set environment variables, create directories

inputs:
  disable_ccache:
    description: Whether ccache should be disabled
    required: true

runs:
  using: composite
  steps:
    - name: Delete old build tools installed using Homebrew (macOS)
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: |
        brew uninstall --force \
          cmake \
          conan

    - name: Install build tools using Homebrew (macOS)
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: |
        brew install --quiet \
          ca-certificates \
          ccache \
          clang-build-analyzer \
          coreutils \
          ninja \
          python@3.14

    - name: Install build tools using pip (macOS)
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: |
        pip3 install --break-system-packages --upgrade pip
        pip3 install --break-system-packages \
          cmake==4.1.2 \
          conan==2.22.1

    - name: Set up Python (Windows)
      if: ${{ runner.os == 'Windows' }}
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
      with:
        python-version: 3.13
    - name: Install build tools using pip (Windows)
      if: ${{ runner.os == 'Windows' }}
      shell: bash
      run: |
        pip install conan==2.22.1

    - name: Fix git permissions (Linux)
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: git config --global --add safe.directory "$PWD"

    - name: Set env variables (macOS)
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: |
        echo "CCACHE_DIR=${{ github.workspace }}/.ccache" >> $GITHUB_ENV
        echo "CONAN_HOME=${{ github.workspace }}/.conan2" >> $GITHUB_ENV

    - name: Set env variables (Linux)
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        echo "CCACHE_DIR=/root/.ccache" >> $GITHUB_ENV
        echo "CONAN_HOME=/root/.conan2" >> $GITHUB_ENV

    - name: Set env variables (Windows)
      if: ${{ runner.os == 'Windows' }}
      shell: bash
      run: |
        echo "CCACHE_DIR=${{ github.workspace }}\.ccache" >> $GITHUB_ENV
        echo "CONAN_HOME=${{ github.workspace }}\.conan2" >> $GITHUB_ENV

    - name: Set CCACHE_DISABLE=1
      if: ${{ inputs.disable_ccache == 'true' }}
      shell: bash
      run: |
        echo "CCACHE_DISABLE=1" >> $GITHUB_ENV

    - name: Create directories
      shell: bash
      run: |
        mkdir -p "$CCACHE_DIR"
        mkdir -p "$CONAN_HOME"
