name: Prepare runner
description: Install packages, set environment variables, create directories

inputs:
  disable_ccache:
    description: Whether ccache should be disabled
    required: true

runs:
  using: composite
  steps:
    - name: Install build tools (macOS)
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: |
        brew install --quiet \
          ca-certificates \
          ccache \
          clang-build-analyzer \
          coreutils \
          cmake \
          conan \
          ninja
        echo "/opt/homebrew/opt/conan@2/bin" >> $GITHUB_PATH

    - name: Set up Python (Windows)
      if: ${{ runner.os == 'Windows' }}
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: 3.13
    - name: Install build tools (Windows)
      if: ${{ runner.os == 'Windows' }}
      shell: bash
      run: |
        pip install conan

    - name: Fix git permissions (Linux)
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: git config --global --add safe.directory "$PWD"

    - name: Set env variables (macOS)
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: |
        echo "CCACHE_DIR=${{ github.workspace }}/.ccache" >> $GITHUB_ENV
        echo "CONAN_HOME=${{ github.workspace }}/.conan2" >> $GITHUB_ENV

    - name: Set env variables (Linux)
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        echo "CCACHE_DIR=/root/.ccache" >> $GITHUB_ENV
        echo "CONAN_HOME=/root/.conan2" >> $GITHUB_ENV

    - name: Set env variables (Windows)
      if: ${{ runner.os == 'Windows' }}
      shell: bash
      run: |
        echo "CCACHE_DIR=${{ github.workspace }}\.ccache" >> $GITHUB_ENV
        echo "CONAN_HOME=${{ github.workspace }}\.conan2" >> $GITHUB_ENV

    - name: Set CCACHE_DISABLE=1
      if: ${{ inputs.disable_ccache == 'true' }}
      shell: bash
      run: |
        echo "CCACHE_DISABLE=1" >> $GITHUB_ENV

    - name: Create directories
      shell: bash
      run: |
        mkdir -p "$CCACHE_DIR"
        mkdir -p "$CONAN_HOME"
