name: Encrypt token
description: GPG-encrypt and base64-encode a token

inputs:
  token:
    description: The token to encrypt
    required: true
  gpg_passphrase:
    description: The GPG passphrase to encrypt the token with
    required: true

outputs:
  token:
    description: The base64-encoded, GPG-encrypted token
    value: ${{ steps.encrypt.outputs.token }}

runs:
  using: composite
  steps:
    - name: Encrypt token
      id: encrypt
      shell: bash
      env:
        TOKEN: ${{ inputs.token }}
        GPG_PASSPHRASE: ${{ inputs.gpg_passphrase }}
      run: |
        ENC_TOKEN=$(gpg --symmetric --batch --passphrase "${GPG_PASSPHRASE}" --output - <(echo -n "${TOKEN}") | base64 -w0)
        echo "token=${ENC_TOKEN}" >> "${GITHUB_OUTPUT}"
