name: Check PR title

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  check_title:
    runs-on: ubuntu-latest

    steps:
      - uses: ytanikin/pr-conventional-commits@fda730cb152c05a849d6d84325e50c6182d9d1e9 # 1.5.1
        # This workflow is used in both pull_request and merge_queue events.
        # But we only want to check the title for pull requests, not for merge queue events.
        #
        # In merge queue events, the PR titles are already validated in individual PRs.
        #
        # Since the check is required, we still have to run the action, but it turns out to be no-op for merge queue events.
        if: ${{ github.event_name == 'pull_request' }}
        with:
          task_types: '["build", "feat", "fix", "docs", "test", "ci", "style", "refactor", "perf", "chore"]'
          add_label: false

      - name: Check if title starts with capital letter after prefix
        if: ${{ github.event_name == 'pull_request' }}
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: |
          if [[ ! "${TITLE}" =~ ^[a-z]+:\ [\[A-Z] ]]; then
            echo "Error: Title must start with an uppercase letter after the prefix."
            exit 1
          fi
