on:
  pull_request:
    paths:
      - ".github/workflows/test-configure-git.yml"
      - "configure-git/**"
  push:
    branches: [main]
    paths:
      - ".github/workflows/test-configure-git.yml"
      - "configure-git/**"
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

defaults:
  run:
    shell: bash

jobs:
  test-configure-git:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Run configure-git
        uses: ./configure-git
        with:
          user_name: Test User
          user_email: test-user@example.com

      - name: Confirm results
        env:
          USER_NAME: Test User
          USER_EMAIL: test-user@example.com
        run: |
          if [[ "$(git config --global user.name)" != "${USER_NAME}" ]]; then
            echo "Unexpected git user.name"
            exit 1
          fi
          if [[ "$(git config --global user.email)" != "${USER_EMAIL}" ]]; then
            echo "Unexpected git user.email"
            exit 1
          fi
