name: Build actions-test Docker images

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build-multiarch-image.yml"
      - ".github/workflows/reusable-build-docker-image.yml"
      - ".github/workflows/test-build-multiarch-image.yml"
      - "test/image/**"
  pull_request:
    paths:
      - ".github/workflows/build-multiarch-image.yml"
      - ".github/workflows/reusable-build-docker-image.yml"
      - ".github/workflows/test-build-multiarch-image.yml"
      - "test/image/**"
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && github.sha || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build-merge:
    name: Build and push test multiarch actions-test image
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        distro:
          - name: debian
            base_image: debian:bookworm
          - name: rhel
            base_image: registry.access.redhat.com/ubi9/ubi:latest
    uses: ./.github/workflows/build-multiarch-image.yml
    with:
      image_name: actions/actions-test-${{ matrix.distro.name }}
      dockerfile: test/image/Dockerfile
      base_image: ${{ matrix.distro.base_image }}
      push: ${{ github.repository == 'XRPLF/actions' && github.event_name != 'pull_request' }}
